tests: install org.flatpak.Authenticator.Oci.service
Otherwise the installed tests will fail:

SUMMARY: total=32; passed=30; skipped=0; failed=2; user=820.8s; system=589.3s; maxrss=445132
FAIL: flatpak/test-oci-registry@user.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-oci-registry@system.wrap.test (Child process exited with code 1)

due to:

error: The name org.flatpak.Authenticator.Oci was not provided by any .service files